import type { FeedScoutDailyFeed } from "./feed-scout";

export const externalFeedScoutDailyFixture: FeedScoutDailyFeed = {
  schema: "farplane_feed_scout_daily",
  schemaVersion: "0.2.0",
  date: "2026-07-02",
  generatedAt: "2026-07-02T03:21:58Z",
  configRef: "farplane/bindings.yaml#feed_scout",
  reviewWindow: "daily",
  summary: {
    actionableItemCount: 4,
    changedItemCount: 4,
    groupCount: 2,
    sourceCount: 4,
    itemCount: 4,
    newItemCount: 4,
    sourceGapCount: 0,
  },
  groups: [
    {
      id: "farplane-ui",
      name: "Farplane UI",
      kind: "project",
      tags: ["product", "ui"],
      itemCount: 4,
      sources: [],
    },
  ],
  items: [
    {
      canonicalKey: "rss-design-systems-weekly-agent-panels",
      canonicalUrl: "https://example.com/design-systems-agent-panels",
      entityGroupId: "farplane-ui",
      entityGroupName: "Farplane UI",
      sourceId: "design-systems-weekly",
      sourceName: "Design Systems Weekly",
      platform: "rss",
      kind: "article",
      rank: 1,
      title: "Designing dense agent workspaces without burying the feed",
      summary: "A compact fixture item for external article rendering.",
      publishedAt: "2026-07-02T09:15:00Z",
      discoveredAt: "2026-07-02T10:00:00Z",
      status: "new",
      evidenceRefs: ["fixture:article"],
      tags: ["dashboard", "workflow"],
    },
    {
      canonicalKey: "youtube-agent-ops-observable-workflows",
      canonicalUrl: "https://youtube.com/watch?v=agent-ops",
      entityGroupId: "farplane-ui",
      entityGroupName: "Farplane UI",
      sourceId: "agent-ops-channel",
      sourceName: "Agent Ops Channel",
      platform: "youtube",
      kind: "video",
      rank: 2,
      title: "Observable AI workflows for small product teams",
      summary: "A compact fixture item for external video rendering.",
      publishedAt: "2026-07-02T08:00:00Z",
      discoveredAt: "2026-07-02T10:00:00Z",
      status: "new",
      evidenceRefs: ["fixture:video"],
      tags: ["agents", "ops"],
    },
    {
      canonicalKey: "github-release-react-flow-ux",
      canonicalUrl: "https://github.com/example/react-flow/releases/tag/v1.2.3",
      entityGroupId: "farplane-ui",
      entityGroupName: "Farplane UI",
      sourceId: "react-flow-releases",
      sourceName: "React Flow Releases",
      platform: "github",
      kind: "release",
      rank: 3,
      title: "React Flow ships compact graph interaction helpers",
      summary: "A compact fixture item for release rendering.",
      publishedAt: "2026-07-02T06:30:00Z",
      discoveredAt: "2026-07-02T10:00:00Z",
      status: "new",
      evidenceRefs: ["fixture:release"],
      tags: ["graph", "release"],
    },
    {
      canonicalKey: "manual-newsletter-founder-control-loop",
      canonicalUrl: "https://example.com/newsletter/founder-control-loop",
      entityGroupId: "farplane-ui",
      entityGroupName: "Farplane UI",
      sourceId: "operator-newsletter",
      sourceName: "Operator Newsletter",
      platform: "newsletter",
      kind: "post",
      rank: 4,
      title: "Founder control loops that keep autonomous teams legible",
      summary: "A compact fixture item for newsletter rendering.",
      publishedAt: "2026-07-01T23:00:00Z",
      discoveredAt: "2026-07-02T10:00:00Z",
      status: "new",
      evidenceRefs: ["fixture:newsletter"],
      tags: ["founder", "autonomy"],
    },
  ],
  sourceGaps: [],
  reportRef: {},
};
